name: PR And Main Build
on:
  push:
    branches:
      - main
  pull_request:
  
jobs:
  build_deploy_test:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      - name: Install Hugo
        run: |
          umask 0002

          sudo apt-get update -y
          wget https://github.com/gohugoio/hugo/releases/download/v0.79.0/hugo_0.79.0_Linux-64bit.deb
          sudo dpkg -i hugo_0.79.0_Linux-64bit.deb

          sudo apt-get install -y tree
      - name: Hugo Build
        run: |
          npm install
          npm run build
          tree .
        env: # Contentful Tokens
          CONTENTFUL_SPACE: ${{ secrets.CONTENTFUL_SPACE }}
          CONTENTFUL_TOKEN: ${{ secrets.CONTENTFUL_TOKEN }}
          CONTENTFUL_PREVIEW_TOKEN: ${{ secrets.CONTENTFUL_PREVIEW_TOKEN }}